apiVersion: cost-mgmt-metrics-cfg.openshift.io/v1beta1
kind: CostManagementMetricsConfig
metadata:
  name: costmanagementmetricscfg-sample
spec:
  authentication:
    type: token
  packaging:
    max_size_MB: 100
  prometheus_config: {}
  source:
    name: INSERT-SOURCE-NAME
    check_cycle: 1440
    create_source: false
  upload:
    upload_cycle: 360
    upload_toggle: false