# permissions for end users to edit kokumetricsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: costmanagementmetricsconfig-editor-role
rules:
- apiGroups:
  - cost-mgmt-metrics-cfg.openshift.io
  resources:
  - kokumetricsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cost-mgmt-metrics-cfg.openshift.io
  resources:
  - costmanagementmetricsconfigs/status
  verbs:
  - get
